from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CurrencyTracker(object):
    def setupUi(self, CurrencyTracker):
        CurrencyTracker.setObjectName("CurrencyTracker")
        CurrencyTracker.resize(600, 400)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        CurrencyTracker.setFont(font)
        CurrencyTracker.setStyleSheet("background-color: rgb(158, 220, 119);")
        self.centralwidget = QtWidgets.QWidget(CurrencyTracker)
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(5, 5, 590, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.title.setFont(font)
        self.title.setStyleSheet("background-color: rgb(240, 240, 240);\n"
"color: rgb(105, 147, 79);")
        self.title.setTextFormat(QtCore.Qt.AutoText)
        self.title.setScaledContents(False)
        self.title.setWordWrap(True)
        self.title.setObjectName("title")
        self.base_value = QtWidgets.QComboBox(self.centralwidget)
        self.base_value.setGeometry(QtCore.QRect(100, 43, 70, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.base_value.setFont(font)
        self.base_value.setObjectName("base_value")
        self.base_value.addItem("")
        self.base_value.addItem("")
        self.base_value.addItem("")
        self.base_value.addItem("")
        self.base_value_txt = QtWidgets.QLabel(self.centralwidget)
        self.base_value_txt.setGeometry(QtCore.QRect(10, 40, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.base_value_txt.setFont(font)
        self.base_value_txt.setObjectName("base_value_txt")
        self.usd_txt = QtWidgets.QLabel(self.centralwidget)
        self.usd_txt.setGeometry(QtCore.QRect(20, 145, 80, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.usd_txt.setFont(font)
        self.usd_txt.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.usd_txt.setObjectName("usd_txt")
        self.eur_txt = QtWidgets.QLabel(self.centralwidget)
        self.eur_txt.setGeometry(QtCore.QRect(20, 190, 80, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.eur_txt.setFont(font)
        self.eur_txt.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.eur_txt.setObjectName("eur_txt")
        self.rub_txt = QtWidgets.QLabel(self.centralwidget)
        self.rub_txt.setGeometry(QtCore.QRect(20, 235, 80, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.rub_txt.setFont(font)
        self.rub_txt.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.rub_txt.setObjectName("rub_txt")
        self.amd_txt = QtWidgets.QLabel(self.centralwidget)
        self.amd_txt.setGeometry(QtCore.QRect(20, 280, 80, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.amd_txt.setFont(font)
        self.amd_txt.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.amd_txt.setObjectName("amd_txt")
        self.usd_valuetxt = QtWidgets.QLabel(self.centralwidget)
        self.usd_valuetxt.setGeometry(QtCore.QRect(100, 145, 80, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.usd_valuetxt.setFont(font)
        self.usd_valuetxt.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.usd_valuetxt.setText("")
        self.usd_valuetxt.setObjectName("usd_valuetxt")
        self.eur_valuetxt = QtWidgets.QLabel(self.centralwidget)
        self.eur_valuetxt.setGeometry(QtCore.QRect(100, 190, 80, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.eur_valuetxt.setFont(font)
        self.eur_valuetxt.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.eur_valuetxt.setText("")
        self.eur_valuetxt.setObjectName("eur_valuetxt")
        self.rub_valuetxt = QtWidgets.QLabel(self.centralwidget)
        self.rub_valuetxt.setGeometry(QtCore.QRect(100, 235, 80, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.rub_valuetxt.setFont(font)
        self.rub_valuetxt.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.rub_valuetxt.setText("")
        self.rub_valuetxt.setObjectName("rub_valuetxt")
        self.amd_valuetxt = QtWidgets.QLabel(self.centralwidget)
        self.amd_valuetxt.setGeometry(QtCore.QRect(100, 280, 80, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.amd_valuetxt.setFont(font)
        self.amd_valuetxt.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.amd_valuetxt.setText("")
        self.amd_valuetxt.setObjectName("amd_valuetxt")
        self.rates_lable = QtWidgets.QLabel(self.centralwidget)
        self.rates_lable.setGeometry(QtCore.QRect(20, 100, 160, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.rates_lable.setFont(font)
        self.rates_lable.setObjectName("rates_lable")
        self.rates_lable_2 = QtWidgets.QLabel(self.centralwidget)
        self.rates_lable_2.setGeometry(QtCore.QRect(330, 100, 185, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.rates_lable_2.setFont(font)
        self.rates_lable_2.setObjectName("rates_lable_2")
        self.base_value_2 = QtWidgets.QComboBox(self.centralwidget)
        self.base_value_2.setGeometry(QtCore.QRect(310, 160, 80, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.base_value_2.setFont(font)
        self.base_value_2.setObjectName("base_value_2")
        self.base_value_2.addItem("")
        self.base_value_2.addItem("")
        self.base_value_2.addItem("")
        self.base_value_2.addItem("")
        self.base_value_3 = QtWidgets.QComboBox(self.centralwidget)
        self.base_value_3.setGeometry(QtCore.QRect(450, 160, 80, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.base_value_3.setFont(font)
        self.base_value_3.setObjectName("base_value_3")
        self.base_value_3.addItem("")
        self.base_value_3.addItem("")
        self.base_value_3.addItem("")
        self.base_value_3.addItem("")
        self.txt_to = QtWidgets.QLabel(self.centralwidget)
        self.txt_to.setGeometry(QtCore.QRect(393, 160, 55, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.txt_to.setFont(font)
        self.txt_to.setStyleSheet("")
        self.txt_to.setObjectName("txt_to")
        self.txt_equal = QtWidgets.QLabel(self.centralwidget)
        self.txt_equal.setGeometry(QtCore.QRect(400, 205, 55, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.txt_equal.setFont(font)
        self.txt_equal.setStyleSheet("")
        self.txt_equal.setObjectName("txt_to")
        self.exchange_value1 = QtWidgets.QTextEdit(self.centralwidget)
        self.exchange_value1.setGeometry(QtCore.QRect(305, 210, 90, 40))
        self.exchange_value1.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.exchange_value1.setObjectName("exchange_value1")
        self.exchange_value2 = QtWidgets.QTextEdit(self.centralwidget)
        self.exchange_value2.setGeometry(QtCore.QRect(445, 210, 90, 40))
        self.exchange_value2.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.exchange_value2.setObjectName("exchange_value2")
        CurrencyTracker.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(CurrencyTracker)
        self.statusbar.setObjectName("statusbar")
        CurrencyTracker.setStatusBar(self.statusbar)

        self.retranslateUi(CurrencyTracker)
        QtCore.QMetaObject.connectSlotsByName(CurrencyTracker)

    def retranslateUi(self, CurrencyTracker):
        _translate = QtCore.QCoreApplication.translate
        CurrencyTracker.setWindowTitle(_translate("CurrencyTracker", "Currency Tracker"))
        self.title.setText(_translate("CurrencyTracker", "Currency Tracker (v 0.1)"))
        self.base_value.setItemText(0, _translate("CurrencyTracker", "Pick"))
        self.base_value.setItemText(1, _translate("CurrencyTracker", "USD"))
        self.base_value.setItemText(2, _translate("CurrencyTracker", "EUR"))
        self.base_value.setItemText(3, _translate("CurrencyTracker", "RUB"))
        self.base_value_txt.setText(_translate("CurrencyTracker", "Base Value"))
        self.usd_txt.setText(_translate("CurrencyTracker", "    USD :"))
        self.eur_txt.setText(_translate("CurrencyTracker", "    EUR :"))
        self.rub_txt.setText(_translate("CurrencyTracker", "    RUB :"))
        self.amd_txt.setText(_translate("CurrencyTracker", "    AMD :"))
        self.rates_lable.setText(_translate("CurrencyTracker", "Currency Rates"))
        self.rates_lable_2.setText(_translate("CurrencyTracker", "Currency Exchange"))
        self.base_value_2.setItemText(0, _translate("CurrencyTracker", "AMD"))
        self.base_value_2.setItemText(1, _translate("CurrencyTracker", "USD"))
        self.base_value_2.setItemText(2, _translate("CurrencyTracker", "EUR"))
        self.base_value_2.setItemText(3, _translate("CurrencyTracker", "RUB"))
        self.base_value_3.setItemText(0, _translate("CurrencyTracker", "AMD"))
        self.base_value_3.setItemText(1, _translate("CurrencyTracker", "USD"))
        self.base_value_3.setItemText(2, _translate("CurrencyTracker", "EUR"))
        self.base_value_3.setItemText(3, _translate("CurrencyTracker", "RUB"))
        self.txt_to.setText(_translate("CurrencyTracker", ": TO :"))
        self.txt_equal.setText(_translate("CurrencyTracker", ": = :"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CurrencyTracker = QtWidgets.QMainWindow()
    ui = Ui_CurrencyTracker()
    ui.setupUi(CurrencyTracker)
    CurrencyTracker.show()
    sys.exit(app.exec_())
